#!/command/with-contenv sh

set -e

# Wait until port 5555 is accepting connections
/usr/local/bin/wait-for-it.sh localhost:5555 -t 30 \
  -- echo "[mod-ui] Port 5555 is ready"

# Now start mod-ui
/usr/local/bin/python3 /mod/mod-ui/server.py  /2>&1 | sed 's/^/[mod-ui] /'