version: '3.6'

services:
  proxy:
    container_name: mado-proxy
    image: mebaxyz/mado-proxy
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - file-api
      - mod-gov
      - modapp  
  file-api:
    container_name: mado-file-api
    image: mebaxyz/mado-file-api
    restart: unless-stopped
    volumes:
      - '/data/user-files:/data'
    ports:
      - '5000:5000'
    environment:
      - USER_FILES_DIR=/data
  mod-gov:
    container_name: mado-gov
    image: mebaxyz/mado-gov
    restart: unless-stopped
    volumes:
      - '/data:/data'
    ports:
      - '8081:8081'

  modapp:
    container_name: lv2-host
    #image: aidadsp/mod-ui:af2945a
    image: mebaxyz/marlise:trixie
    restart: unless-stopped
    read_only: false
    user: "0"
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 95
      memlock: -1
    shm_size: 512m
    environment:
      - 'CARD=UNO'
      - 'SR=48000'
      - 'BUFFER=256'
      - 'TTY=ttymxc3'
      - 'JACK_NO_AUDIO_RESERVATION=1'
      - MOD_DATA_DIR=/data
      - MOD_USER_FILES_DIR=/data/user-files
      - MOD_SOUNDCARD=UNO
    #ports:
    #  - '80:8888'
    volumes:
      - '/dev/shm:/dev/shm'
      - '/system-lv2:/usr/lib/lv2'
      - '/data:/data'
      - '/home/nicolas/mod-ui/mod:/mod/mod-ui/mod'
      - '/home/nicolas/mod-ui/html:/mod/mod-ui/html'
    devices:
      - '/dev/snd:/dev/snd'
#      - '/dev/ttymxc3:/dev/ttymxc3'
#    command: '/entrypoint.sh'
